language: node_js
sudo: required
node_js:
  - "6"
services:
  - mongodb
cache:
   directories:
     - node_modules
env:
  - NODE_ENV=production
notifications:
  slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV